
modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="efck"

version="${mod_version}"

displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.efck]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.efck]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.efck]]
modId="epicfight"
mandatory=true
versionRange="[20.11.7,)"
ordering="BEFORE"
side="BOTH"
